Store and retrieve EDN data in AWS SSM Paramstore

*Why SSM Parameter Store ?*
AWS Systems Manager Parameter Store provides secure, hierarchical
storage for configuration data. It is a great alternative to Consul or
Vault for storing service configuration. Think of it as a managed
Config store in the AWS cloud.

*ednism* provides simple APIs (get, put, history and delete) to store
and retrieve EDN data in paramstore

*ednism* also caches =get= and invalidates the cache on =put=

* Usage

#+BEGIN_SRC clojure
(require '[ednism.core :as e])
(e/login {:provider :profile
          :profile (System/getenv "AWS_PROFILE")
          :region  "us-east-1"})

(e/put "ssm:/my/config/namespace"
       {:a 1
        :b "string"
        :c true
        :e ["a" "b" "c"]
        :d :keyword})

(e/get "ssm:/my/config/namespace")
;; returns the above map in put

(e/history "ssm:/my/config/namespace")

(e/delete "ssm:/my/config/namespace")

#+END_SRC

* License - Apache 2.0

Copyright 2019 Omnyway Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

[[http://www.apache.org/licenses/LICENSE-2.0]]

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
